# Generated by Django 4.2.11 on 2024-04-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_alter_purchaseorder_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPerformance',
            new_name='VendorPerformance',
        ),
    ]
